import { Nunito } from "next/font/google";
import "./globals.css";
import Nav from "@/components/_user/Navbar/Nav";
import Footer from "@/components/_user/Footer/Footer";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Nav />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
